import { useEffect, useState } from 'react';
import type { FormEvent } from 'react';
import { ArrowLeft, ArrowUpRight, Check, Heart, Moon, Sparkles } from 'lucide-react';
import { flushSync } from 'react-dom';
import TogetherScene from './TogetherScene';
import './together.css';

const maxMessage=180;
export default function TogetherApp(){
 const [first,setFirst]=useState(''),[second,setSecond]=useState(''),[promise,setPromise]=useState(''),[shared,setShared]=useState(false),[reduced,setReduced]=useState(false);
 useEffect(()=>{document.title='Một đêm trăng cho hai người · Đêm rằm';const meta=document.querySelector('meta[name="description"]');meta?.setAttribute('content','Hai người, một đêm trăng. Viết một lời hẹn dưới trời rằm.');const motion=matchMedia('(prefers-reduced-motion: reduce)');setReduced(motion.matches);const update=()=>setReduced(motion.matches);motion.addEventListener('change',update);return()=>motion.removeEventListener('change',update)},[]);
 useEffect(()=>{
  const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;
  const lifecycle=new AbortController();const tool={name:'prepare_moon_promise',title:'Soạn lời hẹn dưới trăng',description:'Đặt tên cho hai người và soạn lời hẹn trong giao diện để người dùng tự xem lại rồi gửi lên trăng. Không gửi dữ liệu lên máy chủ.',inputSchema:{type:'object',properties:{firstName:{type:'string',minLength:1,maxLength:32},secondName:{type:'string',minLength:1,maxLength:32},promise:{type:'string',minLength:1,maxLength:maxMessage}},required:['firstName','secondName','promise'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:(input:unknown)=>{const v=input as {firstName?:unknown;secondName?:unknown;promise?:unknown};if(typeof v.firstName!=='string'||!v.firstName.trim()||v.firstName.length>32)throw new Error('Tên đầu tiên cần từ 1 đến 32 ký tự.');if(typeof v.secondName!=='string'||!v.secondName.trim()||v.secondName.length>32)throw new Error('Tên người thương cần từ 1 đến 32 ký tự.');if(typeof v.promise!=='string'||!v.promise.trim()||v.promise.length>maxMessage)throw new Error('Lời hẹn cần từ 1 đến 180 ký tự.');flushSync(()=>{setFirst(v.firstName as string);setSecond(v.secondName as string);setPromise(v.promise as string);setShared(false)});return {status:'promise_prepared',firstName:v.firstName,secondName:v.secondName,awaitingUserSend:true}}};try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{/* Optional browser capability. */}return()=>lifecycle.abort()
 },[]);
 const submit=(e:FormEvent)=>{e.preventDefault();if(!first.trim()||!second.trim()||!promise.trim())return;setShared(true)};
 const reset=()=>{setFirst('');setSecond('');setPromise('');setShared(false)};
 return <main className="together">
  <header className="together-head"><a className="together-back" href="/" aria-label="Về đêm rằm"><ArrowLeft size={17}/><span>Đêm rằm</span></a><a href="/hai-nguoi/" className="together-brand"><span className="together-emblem"><Moon size={22}/></span><span>hai người<span className="together-sub">MỘT ĐÊM TRĂNG</span></span></a><nav aria-label="Các concept Trung thu"><a href="/">Gửi trăng</a><a href="/tiem-banh/">Tiệm bánh</a></nav></header>
  <section className="together-title"><span className="together-kicker"><i/>ĐÊM RẰM, HAI ÁNH ĐÈN</span><h1>Mình hẹn nhau<br/>dưới <em>trăng nhé.</em></h1><p>Đêm nay, giữ một lời hẹn chỉ hai người biết.</p></section>
  <div className="together-scene" aria-label="Hai chú thỏ gặp nhau trên cây cầu nhỏ dưới ánh trăng"><TogetherScene lit={shared} reduced={reduced}/></div>
  <section className="promise-card" aria-label="Lời hẹn dưới trăng">{!shared?<><div className="card-heading"><div><span>GỬI MỘT NGƯỜI THƯƠNG</span><h2>Hai người, một lời hẹn.</h2></div><div className="heart-seal"><Heart size={20}/></div></div><p className="card-copy">Viết tên hai bạn và giữ lại một điều muốn cùng nhau làm.</p><form onSubmit={submit}><div className="names"><label><span>TÊN BẠN</span><input value={first} onChange={e=>setFirst(e.target.value)} placeholder="Người đang ngắm trăng" maxLength={32} required autoComplete="off"/></label><div className="join-heart"><Heart size={16}/></div><label><span>TÊN NGƯỜI ẤY</span><input value={second} onChange={e=>setSecond(e.target.value)} placeholder="Người bạn nhớ đến" maxLength={32} required autoComplete="off"/></label></div><label className="promise-label" htmlFor="promise">ĐIỀU MÌNH MUỐN HẸN NHAU</label><textarea id="promise" value={promise} onChange={e=>setPromise(e.target.value)} placeholder="Mong rằng mùa trăng tới, chúng mình sẽ…" maxLength={maxMessage} required rows={3}/><div className="card-end"><span>{promise.length}/{maxMessage} ký tự</span><span>Chỉ ở lại trên trang này.</span></div><button className="promise-send" type="submit">Thả lời hẹn lên trăng <ArrowUpRight size={18}/></button></form><div className="card-foot"><Sparkles size={14}/> Một lời hẹn nhỏ, một đêm nhớ lâu.</div></>:<div className="promise-result" role="status"><div className="result-check"><Check size={23}/></div><span className="result-label">MỘT LỜI HẸN ĐÃ BAY LÊN</span><h2>{first.trim()} <Heart size={17} fill="currentColor"/> {second.trim()}</h2><p className="promise-quote">“{promise.trim()}”</p><p className="result-note">Trăng làm chứng. Hẹn nhau nhé.</p><button className="promise-send" onClick={reset}>Viết một lời hẹn khác <ArrowUpRight size={18}/></button></div>}</section>
  <div className="together-caption"><span/>Hai chiếc đèn, cùng một khoảng trời.</div>
  <footer className="together-footer"><span>Mùa trăng này, mong mình ở gần nhau.</span><div><Moon size={14}/> RẰM THÁNG TÁM <i/> 2026</div></footer>
 </main>
}
